DOMAIN_NAME:                      {{host_name}}
AWS_ACCESS_KEY_ID:                {{aws_key_id}}
AWS_SECRET_ACCESS_KEY:            {{aws_secret_key}}
ADMIN_EMAIL:                      {{admin_email}}
ADMIN_PASSWORD:                   {{admin_password}}
NEW_RELIC_LICENSE_KEY:            {{new_relic_key}}
ROLLBAR_ACCESS_TOKEN:             {{rollbar_token}}
ROLLBAR_ACCESS_TOKEN_CLIENT_SIDE: {{rollbar_token_client}}

development:
  RAILS_ENV:         production
  RACK_ENV:          production
  HOST:              'localhost:3000'
  MAILTRAP_USER:     {{dev_mailtrap_user}}
  MAILTRAP_PASSWORD: {{dev_mailtrap_password}}
  SECRET_KEY_BASE:   {{dev_secret_key}}

test:
  RAILS_ENV:       test
  RACK_ENV:        test
  SECRET_KEY_BASE: {{test_secret_key}}

staging:
  RAILS_ENV:         staging
  RACK_ENV:          staging
  HOST:              {{staging_host}}
  FOG_DIRECTORY:     {{staging_fog_dir}}
  MAILTRAP_USER:     {{mailtrap_user}}
  MAILTRAP_PASSWORD: {{mailtrap_password}}
  SECRET_KEY_BASE:   {{staging_secret_key}}

production:
  RAILS_ENV:         production
  RACK_ENV:          production
  HOST:              {{host_name}}
  FOG_DIRECTORY:     {{prod_fog_dir}}
  MANDRILL_USERNAME: {{mandrill_username}}
  MANDRILL_APIKEY:   {{mandrill_apikey}}
  SECRET_KEY_BASE:   {{prod_secret_key}}
